[Writable]
LogLevel = 'INFO'
[Writable.StoreAndForward]
Enabled = false
RetryInterval = '5m'
MaxRetryCount = 10

	[Service]
	BootTimeout = "30s"
	CheckInterval = "10s"
	Host = "localhost"
	ServerBindAddr = "" # if blank, uses default Go behavior https://golang.org/pkg/net/#Listen
	Port = 48105
	Protocol = "http"
	ReadMaxLimit = 100
	StartupMsg = "Helix-Remediate Pipeline on MQTT Command Topic Started"
	Timeout = "30s"

	[Registry]
	Host = "localhost"
	Port = 8500
	Type = "consul"

	[Clients]
	 [Clients.Command]
		Protocol = 'http'
		Host = 'localhost'
		Port = 48082

	  [Clients.Logging]
	  Protocol = "http"
	  Host = "localhost"
	  Port = 48061

	[Binding]
	Type="messagebus"
	SubscribeTopic="BMCCommands/#"

	[MessageBus]
	Type = "mqtt"
	    [MessageBus.SubscribeHost]
		Host = "localhost"
		Port = 1883
		Protocol = "tcp"
	    [MessageBus.Optional]
		# MQTT Specific options
		# Client Identifiers
		Username =""
		Password =""
		ClientId ="HelixDWPPipelineClient"
		# Connection information
		Qos          =  "1" # Quality of Sevice values are 0 (At most once), 1 (At least once) or 2 (Exactly once)
		KeepAlive    =  "300" # Seconds (must be 2 or greater)
		Retained     = "true"
		AutoReconnect  = "true"
		ConnectTimeout = "15" # Seconds
		# TLS configuration - Only used if Cert/Key file or Cert/Key PEMblock are specified
		SkipCertVerify = "false"
		CertFile       = ""
		KeyFile        = ""
		KeyPEMBlock    = ""
		CertPEMBlock   = ""

[Logging]
EnableRemote = false
File = './logs/helix-remediate.log'

[ApplicationSettings]
	URL = "https://mobility19-dsom-dwpc.trybmc.com/api/myit-sb/"
	RefLink = "https://mobility19-dsom-dwp.trybmc.com/dwp/app/#/activity"
	Login = "users/login"
	Username = "hannah_admin@petramco.com"
	Password = "Password_1234" 
	
	RequestQ = "requests?requestedfor="
	RequestedFor = "Allen"
	Services = "services/"
	Questionnaire = "questionnaire/answers"
	Request = "requests/"
	Submission = "/submissions"
	
	BMCEventsURL = "http://localhost:48102/api/v1/trigger"

	#TS Database Configuration
	VictoriaMetricsURL = 'http://clm-aus-swwnes.bmc.com:8428'  ## Change this to your Edge Core URL of the form: "http(s)://<core hostname>:8428"

	MetaDataServiceUrl = "http://localhost:48081"
	ElasticURL = "https://clm-aus-swwnes.bmc.com:9200"
	ElasticUser = "admin"
	ElasticPassword = "admin"
	
	node = "Core"
	#node = "Edge"

	PublishMqttHost = 'localhost'
	PublishMqttPort = '1883'
	PublishMqttTopic = 'BMCCommandLog'
	PublishMqttUser = 'admin'
	PublishMqttPassword = 'public'
	PublishMqttQos = '0'
	PublishMqttKeepAlive = '3600'
	PublishMqttClientId = 'CommandExecutionLogPublisher'