// Code generated by mockery v2.38.0. DO NOT EDIT.

package functions

import (
	interfaces "github.com/edgexfoundry/app-functions-sdk-go/v3/pkg/interfaces"
	mock "github.com/stretchr/testify/mock"
)

// MockADEExporterInterface is an autogenerated mock type for the ADEExporterInterface type
type MockADEExporterInterface struct {
	mock.Mock
}

type MockADEExporterInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockADEExporterInterface) EXPECT() *MockADEExporterInterface_Expecter {
	return &MockADEExporterInterface_Expecter{mock: &_m.Mock}
}

// ExportToBHOM provides a mock function with given fields: ctx, data
func (_m *MockADEExporterInterface) ExportToBHOM(ctx interfaces.AppFunctionContext, data interface{}) (bool, interface{}) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for ExportToBHOM")
	}

	var r0 bool
	var r1 interface{}
	if rf, ok := ret.Get(0).(func(interfaces.AppFunctionContext, interface{}) (bool, interface{})); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(interfaces.AppFunctionContext, interface{}) bool); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(interfaces.AppFunctionContext, interface{}) interface{}); ok {
		r1 = rf(ctx, data)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(interface{})
		}
	}

	return r0, r1
}

// MockADEExporterInterface_ExportToBHOM_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportToBHOM'
type MockADEExporterInterface_ExportToBHOM_Call struct {
	*mock.Call
}

// ExportToBHOM is a helper method to define mock.On call
//   - ctx interfaces.AppFunctionContext
//   - data interface{}
func (_e *MockADEExporterInterface_Expecter) ExportToBHOM(ctx interface{}, data interface{}) *MockADEExporterInterface_ExportToBHOM_Call {
	return &MockADEExporterInterface_ExportToBHOM_Call{Call: _e.mock.On("ExportToBHOM", ctx, data)}
}

func (_c *MockADEExporterInterface_ExportToBHOM_Call) Run(run func(ctx interfaces.AppFunctionContext, data interface{})) *MockADEExporterInterface_ExportToBHOM_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interfaces.AppFunctionContext), args[1].(interface{}))
	})
	return _c
}

func (_c *MockADEExporterInterface_ExportToBHOM_Call) Return(_a0 bool, _a1 interface{}) *MockADEExporterInterface_ExportToBHOM_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockADEExporterInterface_ExportToBHOM_Call) RunAndReturn(run func(interfaces.AppFunctionContext, interface{}) (bool, interface{})) *MockADEExporterInterface_ExportToBHOM_Call {
	_c.Call.Return(run)
	return _c
}

// Transform2ADEEvent provides a mock function with given fields: ctx, data
func (_m *MockADEExporterInterface) Transform2ADEEvent(ctx interfaces.AppFunctionContext, data interface{}) (bool, interface{}) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Transform2ADEEvent")
	}

	var r0 bool
	var r1 interface{}
	if rf, ok := ret.Get(0).(func(interfaces.AppFunctionContext, interface{}) (bool, interface{})); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(interfaces.AppFunctionContext, interface{}) bool); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(interfaces.AppFunctionContext, interface{}) interface{}); ok {
		r1 = rf(ctx, data)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(interface{})
		}
	}

	return r0, r1
}

// MockADEExporterInterface_Transform2ADEEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transform2ADEEvent'
type MockADEExporterInterface_Transform2ADEEvent_Call struct {
	*mock.Call
}

// Transform2ADEEvent is a helper method to define mock.On call
//   - ctx interfaces.AppFunctionContext
//   - data interface{}
func (_e *MockADEExporterInterface_Expecter) Transform2ADEEvent(ctx interface{}, data interface{}) *MockADEExporterInterface_Transform2ADEEvent_Call {
	return &MockADEExporterInterface_Transform2ADEEvent_Call{Call: _e.mock.On("Transform2ADEEvent", ctx, data)}
}

func (_c *MockADEExporterInterface_Transform2ADEEvent_Call) Run(run func(ctx interfaces.AppFunctionContext, data interface{})) *MockADEExporterInterface_Transform2ADEEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interfaces.AppFunctionContext), args[1].(interface{}))
	})
	return _c
}

func (_c *MockADEExporterInterface_Transform2ADEEvent_Call) Return(_a0 bool, _a1 interface{}) *MockADEExporterInterface_Transform2ADEEvent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockADEExporterInterface_Transform2ADEEvent_Call) RunAndReturn(run func(interfaces.AppFunctionContext, interface{}) (bool, interface{})) *MockADEExporterInterface_Transform2ADEEvent_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockADEExporterInterface creates a new instance of MockADEExporterInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockADEExporterInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockADEExporterInterface {
	mock := &MockADEExporterInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
