{
 "title": "Helix Edge License Metering (local)",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Host", "label": "Filter By Node", "query": { "query": "label_values(host)" } },
   {
    "name": "query_choice_messages",
    "label": "IoT Messages Type",
    "query": "Metrics Count : hb_in_metrics_count, Metric IoT Messages Count : hb_in_metric_messages_count, Commands Count : hb_commands_count, Command IoT Messages Count : hb_command_messages_count"
   },
   {
    "name": "query_choice_ml",
    "label": "ML Training Minutes",
    "query": "Completed : completed, Canceled : canceled, Terminated : terminated, Failed : failed"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Messages",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(hb_in_metric_messages_count{host=~\"($Host)\"}[$__range])) OR 0 + sum(increase(hb_command_messages_count{host=~\"($Host)\"}[$__range])) OR 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages: ${query_choice_messages} ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(increase(${query_choice_messages}{host=~\"($Host)\"}[5m]), \"custom_legend\", \"($1)\", \"host\", \"(.*)\")",
     "legendFormat": "{{ custom_legend }}"
    }
   ]
  },
  {
   "title": "Total Training (Completed + Canceled)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "sum(increase(hb_completed_jobs_training_time_mins{host=~\"($Host)\"}[$__range])) OR 0 + sum(increase(hb_canceled_jobs_training_time_mins{host=~\"($Host)\"}[$__range])) OR 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ML Training: ${query_choice_ml}",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "label_replace(increase(hb_${query_choice_ml}_jobs_training_time_mins{host=~\"($Host)\"}[$__interval]), \"custom_legend\", \"($1)\", \"host\", \"(.*)\")",
     "legendFormat": "{{ custom_legend }}"
    }
   ]
  },
  {
   "title": "Total Data",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(increase(hb_contextual_data_size_bytes{host=~\"($Host)\"}[$__range]))/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Contextual Data Ingested",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "label_replace(increase(hb_contextual_data_size_bytes{host=~\"($Host)\"}[$__interval])/1024/1024, \"custom_legend\", \"($1)\", \"host\", \"(.*)\")",
     "legendFormat": "{{ custom_legend }}"
    }
   ]
  }
 ]
}