name: Run Make on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-make:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up environment
      run: sudo apt-get update && sudo apt-get install -y make

    - name: Run make hedge_ml_management
      run: make hedge_ml_management
